###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: service-provider
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.242.137
      port: 8500
      discovery:
        hostname: 192.168.242.1
        service-name: ${spring.application.name}

